### ISSUE TITLE
feat: Add Analyzing screen

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-2024-bebalance#135]
### What feature?

- [ ] Create a screen for giving user more information

### Add screenshots

![image](https://github.com/user-attachments/assets/60b52c03-ee09-4d59-8d37-27533ad9af2c)

**Comment by Helen-Sen** [comment]
Design Issue with Text Wrapping and Zoom Levels:

When adjusting the page zoom, the text inside the element <h1 class="_title_1yp6y_30">We’re Analyzing Your Journey!</h1> behaves inconsistently. At certain zoom levels (50%, 80%, 90%, 100%, 125%, 150%), the text splits into two lines, while at other zoom levels (67%, 75%, 110%), it remains on a single line. According to the design specifications, the text should always be displayed in a single line regardless of the zoom level.

This issue arises because the element is flexible and adjusts its size with zoom changes, which causes the text to wrap differently depending on the zoom percentage.

In contrast, the element below it, <div class="_text_1yp6y_38">, which contains a paragraph of text, scales correctly with the zoom, maintaining consistent formatting and sizing. This discrepancy suggests that the title element's responsiveness to zoom is not aligned with the design's intended behavior.

**Comment by Helen-Sen** [comment]
Open a bug (https://github.com/BinaryStudioAcademy/bsa-2024-bebalance/issues/268) for Windows system.
