### ISSUE TITLE
feat: Create AuthWrapper component

### ISSUE THREAD

**Issue by fshabanov** [BinaryStudioAcademy/bsa-2024-bebalance#189]
### What feature?

Auth Wrapper should contain Header and Sidebar components. Should only be displayed for routes, that need user (inside ProtectedRoute)

**Comment by iqbalalayubbi** [comment]
i want to clarify about my task because i'm little bit confused about this task. So, the Auth Wrapper should contain sidebar and header component's like the image below. Last but not least, can you explain about you say "that do not need user (inside ProtectedRoute)"?.  It's mean the user data should not inside the both component's or somehow?

![Image](https://github.com/user-attachments/assets/badba9aa-1564-4584-a72f-f28436b5dcc9)

**Comment by MarinaBershova** [comment]
Sidebar and header are displayed only to authorized user
