### ISSUE TITLE
feat: Create checkbox categories form

### ISSUE THREAD

**Issue by revenets** [BinaryStudioAcademy/bsa-2024-bebalance#250]
### What feature?

Configure Checkbox component to be used as a form input

- [x] Get categories from Backend
- [x] Create a checkbox group form with all categories and additional 'All' option (when 'all' is selected all other checkboxes are selected as well)
- [x] For validation schema either create a custom one within the mobile project or make validation schema optional in `useAppForm`
- [x] On submit for now render the selected categories as a joined string at the bottom of the screen

### Add screenshots
<img width="198" alt="Screenshot 2024-09-01 at 10 47 31" src="https://github.com/user-attachments/assets/553f2c25-eed1-4507-b59f-8922818c62ce">

**Comment by ToyLess78** [comment]
1. Are there any specific validation requirements for this Checkbox that need to be considered?
2. Should we support multiple Checkbox components within a single form?
3. Do we need to provide users with the ability to group Checkbox components within the form?
4. How many checkboxes should be included in the form specifically for this task?
5. Should there be a submit button for the form?
6. Should there be an error message? If so, in what format should it be displayed?

**Comment by revenets** [comment]
> 1. Are there any specific validation requirements for this Checkbox that need to be considered?
> 2. Should we support multiple Checkbox components within a single form?
> 3. Do we need to provide users with the ability to group Checkbox components within the form?
> 4. How many checkboxes should be included in the form specifically for this task?
> 5. Should there be a submit button for the form?
> 6. Should there be an error message? If so, in what format should it be displayed?

Updated the task description

**Comment by ToyLess78** [comment]
![Image](https://github.com/user-attachments/assets/c339566d-f326-4164-8779-b0d3708c8b54)
![Image](https://github.com/user-attachments/assets/28e4876e-dd83-4495-a472-45baf24fc152)



The task Get categories from Backend cannot be completed at this time because the `/categories` route is currently missing on the backend, and its implementation is [not planned](https://github.com/BinaryStudioAcademy/bsa-2024-bebalance/pull/266) for the near future. Therefore, I suggest changing the requirements of this task to remove the dependency on the backend. It might be worth considering alternative options, such as using mock data for the categories or adjusting the task until the backend is ready.

**Comment by anogire** [comment]
Why do you think that getting categories is [not planned](https://github.com/BinaryStudioAcademy/bsa-2024-bebalance/pull/266/files#diff-5b023df44c54f68f3b74c266c8d932a3dd0409871d064eefb97fef02e6916010)?
You can use mock categories for now so that waiting for an endpoint from the backend doesn't block your work.

**Comment by ToyLess78** [comment]
Because the mentioned PR includes a lot of changes, and those changes will take some time. I was planning to create the PR for this issue today.
