### ISSUE TITLE
fix:Incorrect color of sidebar buttons

### ISSUE THREAD

**Issue by MarinaBershova** [BinaryStudioAcademy/bsa-2024-bebalance#406]
### Describe your issue

The sidebar buttons are the incorrect color.
![2024-09-12_16h50_51](https://github.com/user-attachments/assets/151b8001-84d3-43c1-9156-31d1f27e9c35)

### Steps to reproduce

1. Go to http://bebalance.eu-central-1.elasticbeanstalk.com/
2. Sign in to account
3. Pay attention to the sidebar buttons

### What was the actual result?

The sidebar buttons are the incorrect color

### What was the expected result?

The sidebar buttons are black

### Put here any screenshots or videos (optional)

 Buttons should be black.
![image](https://github.com/user-attachments/assets/e8a690af-3fd8-4c8d-a34d-bbfcd9639fe9)

### What OS are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Chrome

### Severity

Minor (S4)

**Comment by MaxKorop** [comment]
On my side, everything works correctly locally, but when I go to the deploy project for the first time, the color of the text only for Settings is blue, and for My Wheel it is black, when I go to Settings, the color of the text becomes black, then I reload the page and this problem is no longer there, even in the future, no matter what I do, it remains black. This bug appeared again in the same order only when I opened the project deployment in another browser, but after I repeated the actions I wrote, I had the same thing as in the previous browser. However, I did not have one like the one on your screen. Could you elaborate on whether the same thing happens to you when you repeat these steps?

**Comment by MarinaBershova** [comment]
I checked, the issue occurs if open the page in incognito mode

**Comment by MarinaBershova** [comment]
The issue has been fixed
